version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: usuariosDB
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
